
version: 0.0
os: linux
files:
  - source: ./
    destination:/home/ubuntu/himadri-app
hooks:
  BeforeInstall:
    - location:  /home/ubuntu/himadri-app/scripts/stop.sh
      runas: ubuntu
  AfterInstall:
    - location:  /home/ubuntu/himadri-app/scripts/start.sh
      runas: ubuntu